language: python # Set the build language to Python

python: 3.6 # Set the version of Python to use

branches: master # Set the branch to build from

install:
    - pip install mkdocs==1.0.4 # Install the required dependencies
    - pip install mkdocs-material==4.6.0
    - pip install Markdown==3.1.1
    - pip install mkdocs-minify-plugin==0.2.1
    - pip install markdown-katex==201912.11b0

script: true

before_deploy:
    - mkdocs build --verbose --clean # Build a local version of the docs
    - echo "docs.oneprocloud.com" > site/CNAME

deploy: # Deploy documentation to Github in the gh_pages branch
    provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    local_dir: site
    on:
        branch: master

after_deploy:
    - git fetch origin gh-pages:gh-pages
    - git push https://${GITEE_USERNAME}:${GITEE_PASSWORD}@gitee.com/oneprocloud/hypermotion_docs master -f
    - git push https://${GITEE_USERNAME}:${GITEE_PASSWORD}@gitee.com/oneprocloud/hypermotion_docs gh-pages:gh-pages -f
